"""
Django settings for quiz_master project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

import environ
env = environ.Env()
environ.Env.read_env()
# settings.py

# Add at the top

# ...

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# ...

# Static files (CSS, JavaScript, images)
STATIC_URL = '/static/'

# Add this for static file handling during development
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# Add this for static file handling during production
# STATIC_ROOT = os.path.join(BASE_DIR, 'static_root')


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-w2-7$)i@le24zqhiq0**n#eg40zgk#r&j8*b4s&$u%^u1y1(m_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = ['*']


CSRF_TRUSTED_ORIGINS = [
    'https://quiz-master-7or3.onrender.com', 'https://*.127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'author',
    "crispy_forms",
    "crispy_bootstrap5",
    "quizm",
]

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"

CRISPY_TEMPLATE_PACK = "bootstrap5"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'quiz_master.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'quiz_master.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = env("EMAIL")
EMAIL_HOST_PASSWORD = env("EMAIL_PASSWORD")


MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


#
# Quiz Master


# For Admin:
# Create Quiz:
# 1. Go the http://127.0.0.1:8000/admin/
# 2. Create a Categories
# 3. create the quizes with the title, Description, select caterory, Qize file, and image


# ### All user:
# #### First Register with poper information and  then  check your gmail for the comfile your mail then login and go the home page
# 1.  the home page with 4-5 section.
# Navbar:
# icon and 6 line and Dashboard dropdowm menu

#  . 1st section has a banner with text

#  . 2nd section some webside related text

#  . 3rd section all quizes with when create and desctiption

#  . 4th section languese used for quizes

#  . 5th section blog

#  . 6h section FAQ and 7th section footer

# 2. Click the homepage start quiz button go the quiz list or click the navbar quizlist button
# 3. All quizes page we see the all caterory quiz and if we click the quiz button then start the quiz.
# 4. For every question you get 10 sec when click submit the you see your score .
# 4. Leaderboard page show all user which user participate the quiz.
# 5. Dashboard page show a dropdowm profile and logout
# 6. profile page see user informations and user can update informations
# 7. about page show about the webside
# 8. contace us page contract form and some address details
