# Generated by Django 4.2.7 on 2024-01-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_quizscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=100, null=True, unique=True),
        ),
    ]
