# Generated by Django 4.2.7 on 2024-01-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_quiz_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='slug',
        ),
        migrations.AddField(
            model_name='quiz',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
    ]
