# Generated by Django 4.2.7 on 2024-01-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_remove_quiz_slug_quiz_average_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='average_rating',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
