# Generated by Django 4.2.7 on 2024-01-24 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizm', '0004_alter_quiz_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='images',
            new_name='image',
        ),
    ]
